### PR TITLE
Make all filesystem requests trigger hooks

### PR DESCRIPTION
**Pull request by oparoz**
@imjalpreet This should make it possible for the app to trigger hooks when external clients are sending files.

### CODE REVIEW

**Comment by imjalpreet** [comment]
@oparoz The hooks are still not being triggered when I am adding the images to the synced folder.

**Comment by oparoz** [comment]
OK, I'm hoping this doesn't mean we have to use the old hooks... Did you try with the other app?

**Comment by imjalpreet** [comment]
I again started trying in the other app yesterday, after I came to know about this problem but I still am not able to get the image Id and the full path in the other method but I will try and come back to you with an update.

**Comment by oparoz** [comment]
The image Id and path, we can figure out later, the top priority for now is to be able to catch events via hooks.
It's supposed to work the way it's described in the documentation, but if it doesn't then we'll need to use the old way.

**Comment by imjalpreet** [comment]
@oparoz Ohk, I will see how to get the image ID and path afterwards, I will first check if it the hooks are triggered due to a sync client in the old method.

**Comment by imjalpreet** [comment]
Issue resolved via [7f48f2c](https://github.com/imjalpreet/MediaMetadata/commit/7f48f2c94c80594f9b1abd87a36b998cf6c000b2)

Thank you, @oparoz.

**Pull request closed without merging**
